.travis.yml, conf.py, index.rst, install.rst, releases/v11_0/known.rst, releases/v11_0/notes.rst, requirements.txt
Use
```
:jirab:`DM-NNNN`
```
roles from Documenteer in existing release notes.
Also enables publication with LSST the Docs.
=> DM-6181: Use reST roles for JIRA references

install/newinstall.rst
The previous ls.st shortlink resulted in a download that didn't have the correct filename.
=> Use full GitHub URL for newinstall.sh download

install/demo.rst
The demo bin/compare command no longer takes the expected output file as an argument.
=> Update demo compare command invocation

install/demo.rst
The --small was being converted into <en-dash>-small.
=> Fix demo --small typography

install/lsstsw.rst
Spurred DM-7552: zsh supports setup.sh, and tcsh can up setup.csh.
=> Update lsstsw instructions for zsh/csh compat.

install/conda.rst, install/index.rst
Because of a (perhaps temporary) divergence in how DM and Sims
distribute their stacks, we're going to entirely de-scope
pipelines.lsst.io from handling sims documentation altogether. Instead
we're adding notices in the installation docs directing sims users to
sims documentation.
- Add a note in install/index.html
- Add notes in install/conda.html at two points to ensure Sims users are
following sims docs instead of DM docs.
=> DM-8961: Direct sims users to sims installation docs

README.md, conf.py, install/newinstall.rst
- ~[ ] Update Python pre-reqs. Perhaps use a Conda manifest from lsstsw, https://github.com/lsst/lsstsw/blob/master/etc/conda2_packages-osx-64.txt~ **DEFERRED.**
https://pipelines.lsst.io/v/DM-9414/install/newinstall.html#macos
=> DM-9414: Update macOS build dependencies (cmake)

.travis.yml
The downtime of docs.scipy.org affects intersphinx, and with the `-W` flag those warnings become errors the fail Travis builds.
See also:
https://community.lsst.org/t/how-docs-scipy-org-and-intersphinx-affect-your-doc-builds/1717?u=jsick
=> DM-9815: Stop warnings from becoming errors because of docs.scipy.org

install/lsstsw.rst, install/newinstall.rst, install/prereqs/index.rst
Updates reporting on OS compatibility.
- Consolidate OS compatibility reporting to a section in `install/prereqs/` so that both the newinstall and lsstsw-based installation pathways can link to it.
- Identify CentOS 7-1611 at the reference platform (see #55)
Drafts:
- https://pipelines.lsst.io/v/DM-11936/install/prereqs/index.html#platform-compatibility
- https://pipelines.lsst.io/v/DM-11936/install/newinstall.html#prerequisites
- https://pipelines.lsst.io/v/DM-11936/install/lsstsw.html#prerequisites
=> DM-11936: 14.0 OS Prerequisites

install/prereqs/index.rst
We require that filesystems used for output of certain files (e.g. persisted configurations, schemas, etc.) support the flock system call.  Tests of this capability in `daf_persistence` also require that the build filesystem have the same support.  There does not appear to be a good way to check for filesystem support, so for now documenting this requirement here seems like the best that can be done.
=> Document the need for flock.

install/setup.rst
Listing packages uses the `eups` command, not the `setup` command.
=> Fix incorrect listing commands.

install/docker.rst
`/home/lsst` is the default user home directory in Docker image `w_2018_06`.  I haven't checked other images.
This line should be changed.  Should the examples be changed to be with respect to `/home/lsst`?
Also, the container opens up in `/opt/lsst/software/stack`.  This is somewhat convenient as you don't have to look up the path for the `loadLSST.bash` script, but perhaps a note to this effect that the containers don't open in the home directory will help the naive user who is completely lost.
=> Update docker.rst to list /home/lsst as container home directory

install/docker.rst
- Use a `[..]-v15_0` tag explicitly in the docs
- Remove old information about the `/home/vagrant` directory that was only relevant for `v14_0`.
Draft: https://pipelines.lsst.io/v/DM-13977/install/docker.html
=> DM-13977: Update Docker instructions for v15_0 release

getting-started/coaddition.rst, getting-started/data-setup.rst, getting-started/display.rst, getting-started/photometry.rst, getting-started/processccd.rst
This PR fixes some API changes that impact the Getting Started tutorial
Note: `15_0_rc2` at least has a bug that affects `makeCoaddTempExp.py`. We're talking about it over on Slack dm-science-pipelines. Depending on whether that's resolvable, we may need to temporarily remove the Getting Started tutorial from the v15 release (or post a warning of some sort).
=> DM-13723: Update Getting Started tutorial for v15.0

install/lsstsw.rst, install/newinstall.rst, install/prereqs/index.rst
With `v16_0` and newer, Python 2.7 is no longer supported. The baseline is Python 3.6.
This PR removes all instructions for installing with Python 2.7.
Also updates the EUPS package roots table.
=> DM-14921: Remove Python 2.7 mentions from installation docs

install/prereqs/index.rst
corrected to point python package dependency to the correct hash (10a4fa6).
=> Python dependencies pointing to the correct has.

metrics.rst
Please review the quick fix: the link to the last characterization report has never been specified in the main Characterization Metric Reports page.
=> DM-15413 fix characterization report for 16.0 rel

requirements.txt
This release includes Astropy integration with intersphinx and enables the `automodsumm_inherited_members` configuration to both inherited members in our Python API references and also to fix issues with entirely missing members.
=> DM-16102: Update to documenteer[pipelines]==0.3.1

.github/CONTRIBUTING.rst, README.md
It turned out that linking to the Jenkins job in the README, it enticed a developer to try running that Jenkins job without going through the documentation to learn how to why to use it, creating a lot of confusion.
Now the README focuses on just saying that the docs are built automatically, and then links to the CONTRIBUTING file that can more carefully guide developers through how to build the documentation.
=> Streamline contrib info in README

requirements.txt
This documenteer release patches the `lsst-task-api-summary` directive to handle cases where an object doesn't have a docstring at all.
=> DM-16398: Update to documenteer 0.4.2

requirements.txt
This release includes a bugfix for lsst-task-config-subtasks that supports introspecting ConfigurableWrapper types.
=> Update documenteer to 0.4.4

conf.py, getting-started/data-setup.rst, index.rst, install/demo.rst, install/docker.rst, install/newinstall.rst, install/prereqs/index.rst, requirements.txt
This PR dynamically versions installation documentation based on the value of the EUPS_TAG environment variable in the build environment. Examples of versioning are:
- URL of `newinstall.sh` file
- EUPS tag
- URL of demo repo archive
- Docker tags
- URL to conda environments
Thus the daily and weekly builds will have accurate installation information, rather than falling back to the old major release info.
This PR depends on PR https://github.com/lsst-sqre/documenteer/pull/60
This work is also currently blocked by an issue with the behavior of the EUPS_TAG variable in Jenkins (it is always `current`, rather than being the specific EUPS tag being built).
You can see a live build of this at https://pipelines.lsst.io/v/DM-17065/ In that deployment, the `EUPS_TAG` variable is `d_2019_02_07`.
=> DM-17065: Automatically version installation docs from EUPS_TAG environment variable

index.rst
This should make the temporary Doxygen API reference site more visible in the interim.
Implements @jdswinbank's suggestion from #117.
=>  Add a link to Doxygen API reference site under the "Modules" homepage section

install/prereqs/debian.rst
Necessary for `fftw`'s `eupspkg.cfg.sh`
=> Add rsync to ubuntu dependencies

releases/note-source/v18_0_0.rst
Merging this branch will permit to include in the 18.0.0 release note the missing information about deprecated APIs.
No software changes are required.
=> DM-20119: Add information on deprecated APIs to 18.0 release notes

index.rst, tasks.rst
[See the Indices section of the draft documentation](https://pipelines.lsst.io/v/DM-20850/index.html#indices).
The [Task index](https://pipelines.lsst.io/v/DM-20850/tasks.html) is made using [our directives for listing tasks](https://documenteer.lsst.io/sphinxext/lssttasks.html#topic-listings) and other objects in the task framework.
The [general index](https://pipelines.lsst.io/v/DM-20850/genindex.html) is built by Sphinx itself and currently indexes all objects documented by domains (namely Python APIs and command-line interfaces). In the future we can start using the [index directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup) to start creating a curated index of concepts.
The Indices section could also be expanded in the future …
=> DM-20850: Add a general index and an index of available tasks

getting-started/data-setup.rst, getting-started/processccd.rst, install/git-lfs.rst, install/lsstsw.rst
DM-19817 updated `ci_hsc` such that the data was pulled out to create a new data-only repo; `testdata_ci_hsc`. This PR updates mentions to `ci_hsc` that should be `testdata_ci_hsc` in docs related to Git LFS and the Getting Started tutorial, which uses the data.
=> DM-21791: Update links to use testdata_ci_hsc

conf.py
The `EUPS_TAG` environment variable in the build environment no longer encodes specific version information so for the 20.0.0 release we need to manually set this information.
=> Hotfix the v20 release tags

gen2tutorialdeprecation.txt, getting-started/coaddition.rst, getting-started/data-setup.rst, getting-started/display.rst, getting-started/index.rst, getting-started/multiband-analysis.rst, getting-started/photometry.rst, getting-started/processccd.rst, index.rst
This change adds a gen2 middleware deprecation notice to the getting started tutorials.
This merge affects the `master` branch. Another PR will also backport this change to the current v21 documentation.
=> DM-30882: Include a gen 2 deprecation notice for tutorials

getting-started/dc2-guide.rst, getting-started/index.rst, index.rst
This guide is intended as a starting place for lsst-devl and/or DP0 users to learn how to process DC2 data through an AP Pipeline. It includes command-line "pipetask run" examples as well as references to the BPS documentation to scale up a single-patch run to an entire tract.
If there is a better place for this to land, please let me know.
I'll attach a PDF of what the page currently looks like when built to the ticket.
=> DM-30027: Add DC2 data processing guide

getting-started/dc2-guide.rst
During the hack session, we noticed one of the example butler queries didn't work. The revised version should work.
=> DM-32035: Lead the SSP data processing hack session

conf.py, releases/tickets/v23_0_0.rst, releases/v23_0_0.rst
Updated existing 23.0.0 page rather than making a new one
because 23.0.1 is a patch for 23.0.0. We do not expect or
recommend than anyone use 23.0.0 for any reason. For
reproducing DP0.2, the results of single frame processing
will be the same with 23.0.1 and 23.0.0, as this patch includes
no behavior changes to single frame processing.
=> DM-33516: Update release notes for 23.0.1

getting-started/singleframe.rst
We discovered that these examples were incorrect during the bootcamp, and @timj offered a fix.
=> Fix query-data-ids examples in getting started

conf.py
This patches the preset configuration of the matplotlib plot directive from documenteer. In documenteer 0.5 we automatically configure the docs with this extension, but in documenteer 0.6 we stopped adding this extension by default because of compatibility issues with the latest Sphinx. Once we move the Pipelines docs build in ci.lsst.codes to Documenteer 0.6+ we can drop this patch.
=> DM-35368: Fix plot extension patch for documenteer 0.6

conf.py
This configuration is available with documenteer 0.6+, which we're now using from rubin-env-developer.
This provides a forward migration route to incorporating the Doxygen build into the site, solves issues with Python recursion issues.
=> DM-38140: Adopt documenteer.conf.pipelines config

conf.py
This configuration is available with documenteer 0.6+, which we're now using from rubin-env-developer.
=> DM-38140-v25: Adopt documenteer.conf.pipelines config

conf.py
networkx is a graph library used in some `pipe_base` APIs; it was added to the `pipe_base` documentation build on lsst/pipe_base#317.
=> DM-36162: Add intersphinx entry for networkx.

middleware/faq.rst
@TallJimbo didn't we have a discussion somewhere about `getStaticDimensions` probably being a bad idea and we needed to add `.names` back in?
=> DM-39605: Use butler.dimensions and fix .names example

getting-started/data-setup.rst, getting-started/display.rst, middleware/faq.rst, releases/v25_0_0.rst
Also fixed v25 change log. @mwittgen this will need to be backported to the v25 branch.
=> DM-40150: Remove deprecated middleware API call to getDirect

install/git-lfs.rst
Our instructions had gotten stale since the move to Giftless.
=> Rectify Git-LFS instructions to match 2024 reality

getting-started/coaddition.rst, getting-started/data-setup.rst, getting-started/uber-cal.rst
There were two steps that were not working as written:
1. `GbdesAstrometricFitTask` has been replaced with `gbdesAstrometricFit`
2. Coaddition now requires `selectDeepCoaddVisits` to be run before `assembleCoadd`.
With these two changes in place, I otherwise confirmed that the tutorial succeeds with `v28_0_0_rc2`.
=> SP-1861: Help DM with their "getting started" tutorial by checking how it fails with v28

index.rst
Provide links to packages included in the Science Pipelines which are documented by external websites, including astro_metadata_translator, sdm_schemas, and felis.
=> DM-47809: Add section with links to external documentation sites
