install/conda.rst
I'm not entirely sure if this note is in the right place. It is now a warning in the relevant section but maybe you really want a troubleshooting section at the end?
=> Add a note to be aware of EUPS_DIR and EUPS_PATH being set

install/newinstall.rst
Also alphasorted the dependencies
=> Added two dependencies required by Ubuntu 16.04

install/newinstall.rst
Using the tagged newinstall.sh script from https://raw.githubusercontent.com/lsst/lsst/v12/scripts/newinstall.sh
=> Update newinstall.sh script to GitHub location

install/newinstall.rst
Also removed jre-7 dependency which was left by mistake on u16
=> Fixed missing continuation

install/newinstall.rst
Corresponds to the new release branch name.
=> Update v12.0 newinstall.sh link

README.md
=> Update README with extra docs

index.rst, releases/README.md, releases/index.rst, releases/notes.rst, releases/v12_0.rst
https://pipelines.lsst.io/v/DM-6608/
=> DM-6608: Add v12.0 release announcement 

known-issues.rst
https://pipelines.lsst.io/v/u-fe-2/
=> v12 Known Issues Update

releases/note-source/v12_0.rst
Change "Camera-specific variants of ProcessCcdTask." to
"Camera-specific variants of ProcessCcdTask are gone."
=> Add missing "are gone"

install/conda.rst, install/index.rst, install/lsstsw.rst, install/newinstall.rst
Tested this locally and works fine.
=> Changed relative to absolute url to correct link.

index.rst
See https://jira.lsstcorp.org/browse/RFC-319
=> Update Doxygen link to point to doxygen.lsst.codes

install/demo.rst
- Incorporates and rebases #44
- Additional tweaks for readability. Actually, these docs need a lot of work to separate actions for explanations. We'll get to that later.
=> Update demo docs for lsstsw

index.rst, install/docker.rst, install/index.rst, install/lsstsw.rst, install/newinstall.rst, install/package-development.rst, install/setup.rst, install/top-level-packages.rst
Draft: https://pipelines.lsst.io/v/DM-12009/index.html#installation
This PR follows on #54, which developed most of the content but was merged early at Frossie's request. The main PR integrating v14 onto master is #57.
=> DM-12009: v14 Installation documentation edits

index.rst
=> move off dm.lssst.org

index.rst
Demonstrating a feature, not substantive
=> Minor edit

Makefile, getting-started/coaddition.rst, getting-started/data-setup.rst, getting-started/index.rst, getting-started/photometry.rst, getting-started/processccd.rst, index.rst, install/git-lfs.rst, install/index.rst, install/lsstsw.rst
This ticket follows DM-10637, the addition of a Getting Started tutorial series based on DMTN-023, and is a means for reviewing that work before it is merged.
Draft content root: https://pipelines.lsst.io/v/DM-11391/getting-started/index.html
=> DM-11391: Getting Started Tutorial (core)

LICENSE, README.md, conf.py, releases/note-source/v12_0.rst
- Update `CURRENT_RELEASE` in `conf.py` to 15.0.
- Update copyright statements for 2018.
- Use correct CC-BY-4.0 license text for metadata detection.
=> 15.0 version bump

releases/note-source/v15_0.rst, releases/v15_0.rst
https://pipelines.lsst.io/v/DM-13940/releases/notes.html#release-v15-0
=> DM-13940:  Update high level release notes

index.rst
=> Update URL for CernVM FS

install/demo.rst, install/docker.rst, install/newinstall.rst, releases/note-source/v16_0.rst, releases/v16_0.rst
Please have a look to these (trivial) changes.. I hope I have no more 15.0 laying around...
Before merging this branch, we should merge John's branch:
https://github.com/lsst/pipelines_lsst_io/tree/u/swinbank/16.0-tickets
=> Updated rst files to refer to 16.0 release

install/prereqs/index.rst, known-issues.rst, releases/note-source/v16_0.rst
I have added a couples of entries following DM-15074.
Can you please review if the phrasing is appropriate and technically the changes are consistent?
=> Known issues and release scope for environment def

requirements.txt
This is the release that contains stack-docs CLI and the Sphinx directives for creating package toctrees.
=> DM-15802: Use documenteer 0.3.0

requirements.txt
This release of [Documenteer](https://documenteer.lsst.io) includes new Sphinx extensions for documenting tasks.
=> Update Documenteer to 0.4.0

requirements.txt
This release includes all the sphinx-jinja work to automate installation docs and the table file based curation of packages. As well, it adds astro_metadata_translator and firefly_client to the intersphinx setup.
=> DM-17263: Update to documenteer 0.5 release

index.rst
Thoughts on this revised wording, @jdswinbank ?
=> Update wording for Doxygen site link.

getting-started/multiband-analysis.rst
It might be nice to add error bars to the `r-i vs. i` scatter plot (since they're available as the second column of that array). I'm not sure what the best way to do that is, nor how to check the code.
=> DM-15849: Cleanup Calib and zero point references in documentation

releases/index.rst, releases/note-source/v19_0_0.rst, releases/note-source/v20_0_0.rst, releases/notes.rst, releases/tickets-source/v20_0_0.rst, releases/tickets.rst, releases/v20_0_0.rst
This includes all currently-known pending deprecations, and deprecations carried over from 19.0.0.
=> DM-23367: Sketch of 20.0.0 release notes

index.rst
With thanks to @manning-ncsa ; replaces #151 .
=> Update definition of LSST

install/newinstall.rst
Also clean up the miniconda/environment description a bit.
=> Prefer "mamba install".

getting-started/coaddition.rst, getting-started/singleframe.rst, getting-started/uber-cal.rst
The changes to the tutorial on this branch are for [DM-35378](https://jira.lsstcorp.org/browse/DM-35378), but because there were changes required to rc2_subset on DM-35723, I used that ticket for this branch. Both should be reviewed together.
=> DM-35723: Add singleFrame subset to DRP.yaml in rc2_subset

getting-started/coaddition.rst
Confirmed by Tim J. that one minor change to makeWarp fixes the issue.
=> DM-36354: Tutorial is broken in warping step

getting-started/dc2-guide.rst
This PR is an up-to-date walkthrough of processing DC2 data with the AP Pipelines on the USDF.
=> PREOPS-1285: Update DC2 AP getting started guide

getting-started/coaddition.rst, getting-started/uber-cal.rst
Replace jointcal task with GbdesAstrometricFitTask.
=> DM-39759: Replace all mentions of jointcal with gbdes.

middleware/faq.rst
=> DM-41365: Use Butler.find_dataset API in middleware FAQ

releases/tickets/v24_1_0.rst, releases/v24_1_0.rst
Rendered here: https://pipelines.lsst.io/v/tickets-DM-41483-main
=> DM-41483 -main: Update release notes for v24.1.1

getting-started/coaddition.rst, getting-started/data-setup.rst, getting-started/display.rst, getting-started/multiband-analysis.rst, getting-started/singleframe.rst, getting-started/uber-cal.rst, install/docker.rst, install/lsstinstall.rst, install/newinstall.rst, install/package-development.rst, install/setup.rst, middleware/faq.rst, releases/v24_0_0.rst
This is one piece of the Jira ticket PREOPS-3431. I still need to identify/assign a reviewer, but in any case I expect that review will be very quick. Thanks very much...
=> PREOPS-3431: address various minor items such as typos in the docs

getting-started/dc2-guide.rst
Changed `LsstCamImSim` to `LSSTCam-imSim` in response to RFC-775.
=> DM-33453: Update pipeline references in response to RFC-775.

middleware/faq.rst
Updated the middleware FAQ to prefer the use of methods from the new query system where available, and reflect the current status of the code.
=> DM-46389: Update middleware FAQ for new query system
